# Business Source License 1.1
# Copyright (c) 2026 OpenWatch

FROM python:3.12-slim
WORKDIR /app
COPY requirements_lite.txt .
RUN pip install --no-cache-dir -r requirements_lite.txt
COPY . .
EXPOSE 8000
CMD ["uvicorn", "main_lite:app", "--host", "0.0.0.0", "--port", "8000"]
